on:
  workflow_dispatch:

jobs:
  run_test:
    uses: MicroFocus/lrc-gh-action/.github/workflows/lrc.yml@bfab9144e5f7acd7565527e7fc57d2deb3869740
    with:
      lrc_server: 'https://srl-qa1.saas.microfocus.com'
      lrc_tenant: '516042910'
      lrc_project: '1'
      lrc_test_id: '363'
    secrets:
      LRC_CLIENT_ID: ${{ secrets.LRC_CLIENT_ID }}
      LRC_CLIENT_SECRET: ${{ secrets.LRC_CLIENT_SECRET }}
  print_run_id:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - run: echo "LRC Run ID is ${{ needs.run_test.outputs.lrc_run_id }}"
